#!/usr/bin/env python3
"""
ANVEL Cross-Chain DEX Trading Strategies

Production-grade automated trading strategies designed for:
- Multi-chain DEX arbitrage
- Liquidity provision optimization
- Momentum/trend following
- Mean reversion
- Flash loan arbitrage

All strategies are:
- Fully automated with risk controls
- Cross-chain compatible (L1, L2, L3)
- DEX-only (no centralized exchanges)
- Designed for the pooled trading system

PRODUCTION-CRITICAL: Handles real capital across multiple chains.
"""

import logging
import threading
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from decimal import Decimal, ROUND_DOWN
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple
from collections import deque
import hashlib
import secrets
import statistics

from anvel_pooled_trading_engine import (
    SUPPORTED_CHAINS,
    SUPPORTED_DEXES,
    ChainLayer,
)

logger = logging.getLogger(__name__)


# ==============================================================================
# CONSTANTS
# ==============================================================================

# Risk management defaults
DEFAULT_MAX_POSITION_SIZE_PCT = Decimal("0.05")  # 5% max per position
DEFAULT_MAX_DAILY_LOSS_PCT = Decimal("0.03")  # 3% max daily loss
DEFAULT_STOP_LOSS_PCT = Decimal("0.02")  # 2% stop loss
DEFAULT_TAKE_PROFIT_PCT = Decimal("0.03")  # 3% take profit

# Strategy execution
MIN_PROFIT_THRESHOLD_BPS = 10  # 0.1% minimum profit for execution
GAS_BUFFER_MULTIPLIER = Decimal("1.2")  # 20% gas buffer
SLIPPAGE_TOLERANCE_BPS = 50  # 0.5% default slippage

# Cross-chain timing
BLOCK_CONFIRMATION_WAIT = {
    ChainLayer.LAYER_1: 12,  # ~3 minutes on Ethereum
    ChainLayer.LAYER_2: 1,   # Near instant on L2s
    ChainLayer.LAYER_3: 1,   # Near instant on L3s
}


# ==============================================================================
# ENUMS
# ==============================================================================

class StrategyType(Enum):
    """Types of trading strategies."""
    ARBITRAGE = "arbitrage"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    LIQUIDITY = "liquidity"
    FLASH_LOAN = "flash_loan"
    GRID = "grid"
    DCA = "dca"
    TWAP = "twap"
    VWAP = "vwap"
    STAT_ARB = "stat_arb"


class SignalType(Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


class StrategyState(Enum):
    """Strategy execution state."""
    IDLE = "idle"
    SCANNING = "scanning"
    EXECUTING = "executing"
    COOLING_DOWN = "cooling_down"
    PAUSED = "paused"
    ERROR = "error"


# ==============================================================================
# DATA CLASSES
# ==============================================================================

@dataclass
class TradingSignal:
    """A trading signal generated by a strategy."""
    signal_id: str
    strategy_type: StrategyType
    signal_type: SignalType
    chain_id: int
    dex_name: str
    token_in: str
    token_out: str
    amount: Decimal
    expected_output: Decimal
    expected_profit_bps: int
    confidence: float  # 0.0 to 1.0
    timestamp: int
    expires_at: int
    metadata: Dict[str, Any] = field(default_factory=dict)

    def is_valid(self) -> bool:
        """Check if signal is still valid."""
        return time.time() < self.expires_at and self.confidence >= 0.5


@dataclass
class ArbitrageOpportunity:
    """Cross-chain or cross-DEX arbitrage opportunity."""
    opportunity_id: str
    source_chain_id: int
    source_dex: str
    target_chain_id: int
    target_dex: str
    token_address: str
    source_price: Decimal
    target_price: Decimal
    profit_bps: int
    max_amount: Decimal
    gas_cost_estimate: Decimal
    net_profit_estimate: Decimal
    timestamp: int
    is_cross_chain: bool


@dataclass
class StrategyConfig:
    """Configuration for a trading strategy."""
    strategy_type: StrategyType
    enabled: bool = True
    max_position_size_pct: Decimal = DEFAULT_MAX_POSITION_SIZE_PCT
    max_daily_loss_pct: Decimal = DEFAULT_MAX_DAILY_LOSS_PCT
    stop_loss_pct: Decimal = DEFAULT_STOP_LOSS_PCT
    take_profit_pct: Decimal = DEFAULT_TAKE_PROFIT_PCT
    min_profit_threshold_bps: int = MIN_PROFIT_THRESHOLD_BPS
    slippage_tolerance_bps: int = SLIPPAGE_TOLERANCE_BPS
    cooldown_seconds: int = 60
    max_trades_per_hour: int = 10
    chain_ids: List[int] = field(default_factory=list)
    dex_names: List[str] = field(default_factory=list)
    custom_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyMetrics:
    """Performance metrics for a strategy."""
    total_signals: int = 0
    executed_signals: int = 0
    profitable_trades: int = 0
    losing_trades: int = 0
    total_profit: Decimal = Decimal("0")
    total_loss: Decimal = Decimal("0")
    win_rate: float = 0.0
    avg_profit_per_trade: Decimal = Decimal("0")
    sharpe_ratio: float = 0.0
    max_drawdown: Decimal = Decimal("0")


# ==============================================================================
# BASE STRATEGY CLASS
# ==============================================================================

class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Provides:
    - Risk management framework
    - Signal generation interface
    - Execution hooks
    - Performance tracking
    """

    def __init__(
        self,
        config: StrategyConfig,
        price_feed: Optional[Callable[[str, int], Decimal]] = None,
    ):
        """
        Initialize strategy.
        
        Args:
            config: Strategy configuration
            price_feed: Optional callable to get price for token on chain
        """
        self.config = config
        self.price_feed = price_feed
        self.state = StrategyState.IDLE
        self.metrics = StrategyMetrics()
        
        self._lock = threading.Lock()
        self._last_execution_time = 0
        self._daily_loss = Decimal("0")
        self._daily_trades = 0
        self._trade_history: deque = deque(maxlen=1000)
        self._signals: deque = deque(maxlen=100)
        
        logger.info(
            "Strategy initialized: type=%s, enabled=%s",
            config.strategy_type.value,
            config.enabled,
        )

    @property
    def strategy_type(self) -> StrategyType:
        """Get strategy type."""
        return self.config.strategy_type

    @abstractmethod
    def generate_signals(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """
        Generate trading signals based on market data.
        
        Args:
            market_data: Current market state including prices, volumes, etc.
            
        Returns:
            List of trading signals
        """
        pass

    @abstractmethod
    def validate_opportunity(
        self,
        signal: TradingSignal,
        current_prices: Dict[str, Decimal],
    ) -> bool:
        """
        Validate that an opportunity is still valid before execution.
        
        Args:
            signal: The trading signal to validate
            current_prices: Current market prices
            
        Returns:
            True if opportunity is still valid
        """
        pass

    def can_execute(self) -> Tuple[bool, str]:
        """
        Check if strategy can execute trades.
        
        Returns:
            Tuple of (can_execute, reason_if_not)
        """
        with self._lock:
            if not self.config.enabled:
                return False, "Strategy is disabled"
            
            if self.state == StrategyState.PAUSED:
                return False, "Strategy is paused"
            
            if self.state == StrategyState.ERROR:
                return False, "Strategy is in error state"
            
            # Check cooldown
            time_since_last = time.time() - self._last_execution_time
            if time_since_last < self.config.cooldown_seconds:
                remaining = self.config.cooldown_seconds - time_since_last
                return False, f"Cooldown active: {remaining:.0f}s remaining"
            
            # Check daily loss limit
            if self._daily_loss >= self.config.max_daily_loss_pct:
                return False, "Daily loss limit reached"
            
            # Check hourly trade limit
            hour_ago = time.time() - 3600
            recent_trades = sum(
                1 for t in self._trade_history
                if t.get('timestamp', 0) > hour_ago
            )
            if recent_trades >= self.config.max_trades_per_hour:
                return False, "Hourly trade limit reached"
            
            return True, ""

    def calculate_position_size(
        self,
        available_capital: Decimal,
        signal: TradingSignal,
    ) -> Decimal:
        """
        Calculate appropriate position size based on risk parameters.
        
        Args:
            available_capital: Total available capital
            signal: Trading signal with confidence
            
        Returns:
            Position size in base currency
        """
        # Base size from max position percentage
        max_size = available_capital * self.config.max_position_size_pct
        
        # Adjust by signal confidence (higher confidence = larger position)
        confidence_adjusted = max_size * Decimal(str(signal.confidence))
        
        # Ensure minimum viable position
        min_position = Decimal("10.00")  # $10 minimum
        
        return max(min_position, min(confidence_adjusted, max_size))

    def record_trade(
        self,
        signal: TradingSignal,
        executed: bool,
        profit: Optional[Decimal] = None,
        error: Optional[str] = None,
    ):
        """Record trade for metrics tracking."""
        with self._lock:
            self._trade_history.append({
                'signal_id': signal.signal_id,
                'timestamp': time.time(),
                'executed': executed,
                'profit': float(profit) if profit else None,
                'error': error,
            })
            
            self.metrics.total_signals += 1
            
            if executed:
                self.metrics.executed_signals += 1
                self._last_execution_time = time.time()
                self._daily_trades += 1
                
                if profit:
                    if profit > 0:
                        self.metrics.profitable_trades += 1
                        self.metrics.total_profit += profit
                    else:
                        self.metrics.losing_trades += 1
                        self.metrics.total_loss += abs(profit)
                        self._daily_loss += abs(profit)
            
            # Update win rate
            total_closed = self.metrics.profitable_trades + self.metrics.losing_trades
            if total_closed > 0:
                self.metrics.win_rate = self.metrics.profitable_trades / total_closed
                
                # Average profit per trade
                net = self.metrics.total_profit - self.metrics.total_loss
                self.metrics.avg_profit_per_trade = net / Decimal(total_closed)

    def reset_daily_metrics(self):
        """Reset daily tracking metrics (call at day boundary)."""
        with self._lock:
            self._daily_loss = Decimal("0")
            self._daily_trades = 0

    def pause(self):
        """Pause strategy execution."""
        with self._lock:
            self.state = StrategyState.PAUSED
            logger.info("Strategy paused: %s", self.config.strategy_type.value)

    def resume(self):
        """Resume strategy execution."""
        with self._lock:
            if self.state == StrategyState.PAUSED:
                self.state = StrategyState.IDLE
                logger.info("Strategy resumed: %s", self.config.strategy_type.value)

    def get_metrics(self) -> StrategyMetrics:
        """Get current strategy metrics."""
        with self._lock:
            return self.metrics


# ==============================================================================
# CROSS-CHAIN ARBITRAGE STRATEGY
# ==============================================================================

class CrossChainArbitrageStrategy(BaseStrategy):
    """
    Cross-chain and cross-DEX arbitrage strategy.
    
    Detects and executes arbitrage opportunities across:
    - Different chains (e.g., ETH mainnet vs Arbitrum)
    - Different DEXes on the same chain (e.g., Uniswap vs Sushiswap)
    
    Features:
    - Atomic execution where possible
    - Gas cost consideration
    - Slippage protection
    - Bridge fee accounting for cross-chain arb
    """

    def __init__(
        self,
        config: StrategyConfig,
        price_feed: Optional[Callable[[str, int], Decimal]] = None,
        bridge_fee_estimator: Optional[Callable[[int, int, Decimal], Decimal]] = None,
    ):
        """
        Initialize arbitrage strategy.
        
        Args:
            config: Strategy configuration
            price_feed: Function to get token price on chain
            bridge_fee_estimator: Function to estimate bridge fees
        """
        super().__init__(config, price_feed)
        self.bridge_fee_estimator = bridge_fee_estimator
        
        # Arbitrage-specific configuration
        self.min_profit_after_fees_bps = config.custom_params.get('min_profit_after_fees_bps', 20)
        self.max_bridge_wait_seconds = config.custom_params.get('max_bridge_wait_seconds', 300)
        
        # Track opportunities
        self._opportunities: deque = deque(maxlen=100)

    def generate_signals(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """
        Scan for arbitrage opportunities across chains and DEXes.
        
        Args:
            market_data: Should contain:
                - prices: Dict[chain_id][dex_name][token_address] = price
                - volumes: Dict[chain_id][dex_name][token_address] = volume
                - liquidity: Dict[chain_id][dex_name][token_address] = liquidity
                
        Returns:
            List of arbitrage signals
        """
        signals = []
        prices = market_data.get('prices', {})
        
        if not prices:
            return signals

        # Get all token addresses across all chains/dexes
        all_tokens = set()
        for chain_data in prices.values():
            for dex_data in chain_data.values():
                all_tokens.update(dex_data.keys())

        # For each token, find arbitrage opportunities
        for token in all_tokens:
            opportunities = self._find_arbitrage_opportunities(token, prices, market_data)
            
            for opp in opportunities:
                # Skip if profit too low
                if opp.profit_bps < self.config.min_profit_threshold_bps:
                    continue
                
                # Create signal
                signal = TradingSignal(
                    signal_id=self._generate_signal_id(),
                    strategy_type=StrategyType.ARBITRAGE,
                    signal_type=SignalType.BUY,
                    chain_id=opp.source_chain_id,
                    dex_name=opp.source_dex,
                    token_in=token,
                    token_out=token,  # Same token, different venue
                    amount=opp.max_amount,
                    expected_output=opp.max_amount * (Decimal("1") + Decimal(opp.profit_bps) / Decimal("10000")),
                    expected_profit_bps=opp.profit_bps,
                    confidence=self._calculate_confidence(opp),
                    timestamp=int(time.time()),
                    expires_at=int(time.time()) + 30,  # 30 second validity
                    metadata={
                        'opportunity': {
                            'source_chain': opp.source_chain_id,
                            'target_chain': opp.target_chain_id,
                            'source_dex': opp.source_dex,
                            'target_dex': opp.target_dex,
                            'is_cross_chain': opp.is_cross_chain,
                            'net_profit_estimate': float(opp.net_profit_estimate),
                        }
                    }
                )
                
                signals.append(signal)
                self._opportunities.append(opp)
        
        return signals

    def _find_arbitrage_opportunities(
        self,
        token: str,
        prices: Dict[int, Dict[str, Dict[str, Decimal]]],
        market_data: Dict[str, Any],
    ) -> List[ArbitrageOpportunity]:
        """Find all arbitrage opportunities for a token."""
        opportunities = []
        
        # Collect all price points for this token
        price_points = []
        for chain_id, chain_data in prices.items():
            for dex_name, dex_data in chain_data.items():
                if token in dex_data:
                    price_points.append({
                        'chain_id': chain_id,
                        'dex_name': dex_name,
                        'price': dex_data[token],
                    })
        
        if len(price_points) < 2:
            return opportunities
        
        # Compare all pairs
        for i, source in enumerate(price_points):
            for target in price_points[i+1:]:
                # Calculate price difference
                source_price = source['price']
                target_price = target['price']
                
                if source_price <= 0 or target_price <= 0:
                    continue
                
                # Determine direction (buy low, sell high)
                if source_price < target_price:
                    buy_venue = source
                    sell_venue = target
                    profit_bps = int(((target_price - source_price) / source_price) * 10000)
                else:
                    buy_venue = target
                    sell_venue = source
                    profit_bps = int(((source_price - target_price) / target_price) * 10000)
                
                if profit_bps < self.min_profit_after_fees_bps:
                    continue
                
                is_cross_chain = buy_venue['chain_id'] != sell_venue['chain_id']
                
                # Estimate costs
                gas_cost = self._estimate_gas_cost(
                    buy_venue['chain_id'],
                    sell_venue['chain_id'],
                    is_cross_chain,
                )
                
                bridge_cost = Decimal("0")
                if is_cross_chain and self.bridge_fee_estimator:
                    bridge_cost = self.bridge_fee_estimator(
                        buy_venue['chain_id'],
                        sell_venue['chain_id'],
                        Decimal("1000"),  # Estimate for $1000
                    )
                
                # Calculate net profit
                total_cost = gas_cost + bridge_cost
                trade_amount = Decimal("1000")  # Base calculation on $1000
                gross_profit = trade_amount * Decimal(profit_bps) / Decimal("10000")
                net_profit = gross_profit - total_cost
                
                if net_profit <= 0:
                    continue
                
                # Get max amount based on liquidity
                max_amount = self._get_max_trade_amount(
                    token,
                    buy_venue['chain_id'],
                    buy_venue['dex_name'],
                    market_data.get('liquidity', {}),
                )
                
                opportunities.append(ArbitrageOpportunity(
                    opportunity_id=self._generate_opportunity_id(),
                    source_chain_id=buy_venue['chain_id'],
                    source_dex=buy_venue['dex_name'],
                    target_chain_id=sell_venue['chain_id'],
                    target_dex=sell_venue['dex_name'],
                    token_address=token,
                    source_price=buy_venue['price'],
                    target_price=sell_venue['price'],
                    profit_bps=profit_bps,
                    max_amount=max_amount,
                    gas_cost_estimate=gas_cost,
                    net_profit_estimate=net_profit,
                    timestamp=int(time.time()),
                    is_cross_chain=is_cross_chain,
                ))
        
        return opportunities

    def _estimate_gas_cost(
        self,
        source_chain: int,
        target_chain: int,
        is_cross_chain: bool,
    ) -> Decimal:
        """Estimate gas cost for arbitrage execution."""
        # Base gas costs per chain type (in USD)
        chain = SUPPORTED_CHAINS.get(source_chain)
        if not chain:
            return Decimal("50")  # Conservative default
        
        base_costs = {
            ChainLayer.LAYER_1: Decimal("20"),  # ~$20 on mainnet
            ChainLayer.LAYER_2: Decimal("0.50"),  # ~$0.50 on L2
            ChainLayer.LAYER_3: Decimal("0.10"),  # ~$0.10 on L3
        }
        
        source_cost = base_costs.get(chain.layer, Decimal("10"))
        
        if is_cross_chain:
            target_chain_info = SUPPORTED_CHAINS.get(target_chain)
            if target_chain_info:
                target_cost = base_costs.get(target_chain_info.layer, Decimal("10"))
            else:
                target_cost = Decimal("10")
            return source_cost + target_cost
        
        return source_cost * 2  # Two swaps on same chain

    def _get_max_trade_amount(
        self,
        token: str,
        chain_id: int,
        dex_name: str,
        liquidity_data: Dict,
    ) -> Decimal:
        """Get maximum trade amount based on liquidity."""
        try:
            pool_liquidity = liquidity_data.get(chain_id, {}).get(dex_name, {}).get(token, 0)
            # Max 2% of pool liquidity to minimize price impact
            return Decimal(str(pool_liquidity)) * Decimal("0.02")
        except (KeyError, TypeError):
            return Decimal("1000")  # Default $1000 max

    def _calculate_confidence(self, opp: ArbitrageOpportunity) -> float:
        """Calculate confidence score for opportunity."""
        # Base confidence from profit margin
        profit_confidence = min(1.0, opp.profit_bps / 100)  # Max at 1% profit
        
        # Penalty for cross-chain (more risk)
        cross_chain_penalty = 0.2 if opp.is_cross_chain else 0.0
        
        # Penalty for low net profit
        net_profit_score = min(1.0, float(opp.net_profit_estimate) / 50)  # Max at $50 profit
        
        confidence = (profit_confidence * 0.4 + net_profit_score * 0.4) * (1 - cross_chain_penalty)
        
        return max(0.1, min(0.95, confidence))

    def validate_opportunity(
        self,
        signal: TradingSignal,
        current_prices: Dict[str, Decimal],
    ) -> bool:
        """Validate arbitrage opportunity is still profitable."""
        if not signal.is_valid():
            return False
        
        metadata = signal.metadata.get('opportunity', {})
        source_chain = metadata.get('source_chain')
        target_chain = metadata.get('target_chain')
        
        # Get current prices
        source_price = current_prices.get(f"{source_chain}:{signal.token_in}")
        target_price = current_prices.get(f"{target_chain}:{signal.token_in}")
        
        if not source_price or not target_price:
            return False
        
        # Recalculate profit
        if source_price < target_price:
            current_profit_bps = int(((target_price - source_price) / source_price) * 10000)
        else:
            current_profit_bps = int(((source_price - target_price) / target_price) * 10000)
        
        # Require at least 70% of original expected profit
        return current_profit_bps >= signal.expected_profit_bps * 0.7

    def _generate_signal_id(self) -> str:
        """Generate unique signal ID."""
        return f"ARB-{secrets.token_hex(8).upper()}"

    def _generate_opportunity_id(self) -> str:
        """Generate unique opportunity ID."""
        return f"OPP-{secrets.token_hex(8).upper()}"


# ==============================================================================
# MOMENTUM STRATEGY
# ==============================================================================

class MomentumStrategy(BaseStrategy):
    """
    Momentum/trend following strategy for DEX trading.
    
    Identifies and follows strong price trends across DEX markets.
    Uses multiple timeframe analysis and volume confirmation.
    
    Features:
    - Multi-timeframe trend detection
    - Volume-weighted momentum scoring
    - Breakout detection
    - Trend strength filtering
    """

    def __init__(
        self,
        config: StrategyConfig,
        price_feed: Optional[Callable[[str, int], Decimal]] = None,
    ):
        super().__init__(config, price_feed)
        
        # Momentum-specific configuration
        self.lookback_periods = config.custom_params.get('lookback_periods', [5, 15, 60])  # minutes
        self.min_trend_strength = config.custom_params.get('min_trend_strength', 0.6)
        self.volume_confirmation_multiplier = config.custom_params.get('volume_multiplier', 1.5)
        
        # Price history for analysis
        self._price_history: Dict[str, deque] = {}
        self._volume_history: Dict[str, deque] = {}

    def generate_signals(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """
        Generate momentum signals based on trend analysis.
        
        Args:
            market_data: Should contain:
                - prices: Current prices
                - price_history: Historical prices
                - volumes: Current volumes
                - volume_history: Historical volumes
        """
        signals = []
        
        prices = market_data.get('prices', {})
        price_history = market_data.get('price_history', {})
        volumes = market_data.get('volumes', {})
        volume_history = market_data.get('volume_history', {})
        
        for chain_id in self.config.chain_ids or SUPPORTED_CHAINS.keys():
            chain_prices = prices.get(chain_id, {})
            
            for dex_name in self.config.dex_names or SUPPORTED_DEXES.keys():
                dex_prices = chain_prices.get(dex_name, {})
                
                for token, current_price in dex_prices.items():
                    # Get historical data
                    history_key = f"{chain_id}:{dex_name}:{token}"
                    token_history = price_history.get(history_key, [])
                    token_volumes = volume_history.get(history_key, [])
                    
                    if len(token_history) < max(self.lookback_periods):
                        continue
                    
                    # Calculate momentum score
                    momentum_score = self._calculate_momentum_score(
                        current_price,
                        token_history,
                    )
                    
                    # Check volume confirmation
                    volume_confirmed = self._check_volume_confirmation(
                        token_volumes,
                        volumes.get(chain_id, {}).get(dex_name, {}).get(token, 0),
                    )
                    
                    if not volume_confirmed:
                        momentum_score *= 0.5  # Reduce confidence without volume
                    
                    # Generate signal if momentum is strong enough
                    if abs(momentum_score) >= self.min_trend_strength:
                        signal_type = SignalType.BUY if momentum_score > 0 else SignalType.SELL
                        
                        signals.append(TradingSignal(
                            signal_id=f"MOM-{secrets.token_hex(8).upper()}",
                            strategy_type=StrategyType.MOMENTUM,
                            signal_type=signal_type,
                            chain_id=chain_id,
                            dex_name=dex_name,
                            token_in="USDC" if signal_type == SignalType.BUY else token,
                            token_out=token if signal_type == SignalType.BUY else "USDC",
                            amount=Decimal("0"),  # Calculated at execution
                            expected_output=Decimal("0"),
                            expected_profit_bps=int(abs(momentum_score) * 100),
                            confidence=abs(momentum_score),
                            timestamp=int(time.time()),
                            expires_at=int(time.time()) + 300,  # 5 minute validity
                            metadata={
                                'momentum_score': momentum_score,
                                'volume_confirmed': volume_confirmed,
                                'trend_direction': 'up' if momentum_score > 0 else 'down',
                            }
                        ))
        
        return signals

    def _calculate_momentum_score(
        self,
        current_price: Decimal,
        price_history: List[Decimal],
    ) -> float:
        """
        Calculate momentum score across multiple timeframes.
        
        Returns:
            Score from -1.0 (strong downtrend) to 1.0 (strong uptrend)
        """
        if not price_history:
            return 0.0
        
        scores = []
        
        for period in self.lookback_periods:
            if len(price_history) < period:
                continue
            
            # Get price from 'period' bars ago
            past_price = price_history[-period]
            if past_price <= 0:
                continue
            
            # Calculate return
            returns = (float(current_price) - float(past_price)) / float(past_price)
            
            # Normalize to -1 to 1 (assuming ±10% is extreme)
            normalized = max(-1.0, min(1.0, returns / 0.10))
            scores.append(normalized)
        
        if not scores:
            return 0.0
        
        # Weight shorter timeframes more heavily
        weights = [1.0 / (i + 1) for i in range(len(scores))]
        weighted_sum = sum(s * w for s, w in zip(scores, weights))
        total_weight = sum(weights)
        
        return weighted_sum / total_weight

    def _check_volume_confirmation(
        self,
        volume_history: List[Decimal],
        current_volume: Decimal,
    ) -> bool:
        """Check if current volume confirms the trend."""
        if not volume_history or current_volume <= 0:
            return False
        
        avg_volume = sum(volume_history) / len(volume_history)
        
        return current_volume >= avg_volume * self.volume_confirmation_multiplier

    def validate_opportunity(
        self,
        signal: TradingSignal,
        current_prices: Dict[str, Decimal],
    ) -> bool:
        """Validate momentum signal is still valid."""
        if not signal.is_valid():
            return False
        
        # For momentum, just ensure price hasn't moved against us too much
        original_direction = signal.metadata.get('trend_direction')
        token_key = f"{signal.chain_id}:{signal.dex_name}:{signal.token_out}"
        current_price = current_prices.get(token_key)
        
        if not current_price:
            return True  # Can't validate, assume still valid
        
        return True  # Momentum signals remain valid within expiry


# ==============================================================================
# MEAN REVERSION STRATEGY
# ==============================================================================

class MeanReversionStrategy(BaseStrategy):
    """
    Mean reversion strategy for DEX trading.
    
    Identifies overbought/oversold conditions and trades the reversion.
    
    Features:
    - Bollinger Band analysis
    - RSI-based entry/exit
    - Standard deviation thresholds
    - Convergence detection
    """

    def __init__(
        self,
        config: StrategyConfig,
        price_feed: Optional[Callable[[str, int], Decimal]] = None,
    ):
        super().__init__(config, price_feed)
        
        # Mean reversion specific config
        self.lookback_period = config.custom_params.get('lookback_period', 20)
        self.std_dev_threshold = config.custom_params.get('std_dev_threshold', 2.0)
        self.rsi_oversold = config.custom_params.get('rsi_oversold', 30)
        self.rsi_overbought = config.custom_params.get('rsi_overbought', 70)

    def generate_signals(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """Generate mean reversion signals."""
        signals = []
        
        prices = market_data.get('prices', {})
        price_history = market_data.get('price_history', {})
        
        for chain_id in self.config.chain_ids or SUPPORTED_CHAINS.keys():
            chain_prices = prices.get(chain_id, {})
            
            for dex_name in self.config.dex_names or SUPPORTED_DEXES.keys():
                dex_prices = chain_prices.get(dex_name, {})
                
                for token, current_price in dex_prices.items():
                    history_key = f"{chain_id}:{dex_name}:{token}"
                    token_history = price_history.get(history_key, [])
                    
                    if len(token_history) < self.lookback_period:
                        continue
                    
                    # Calculate statistics
                    recent_prices = [float(p) for p in token_history[-self.lookback_period:]]
                    mean_price = statistics.mean(recent_prices)
                    std_dev = statistics.stdev(recent_prices) if len(recent_prices) > 1 else 0
                    
                    if std_dev == 0:
                        continue
                    
                    # Calculate z-score (how many std devs from mean)
                    z_score = (float(current_price) - mean_price) / std_dev
                    
                    # Calculate RSI
                    rsi = self._calculate_rsi(recent_prices)
                    
                    # Generate signals for extreme deviations
                    signal_type = None
                    confidence = 0.0
                    
                    # Oversold - expect price to rise
                    if z_score < -self.std_dev_threshold and rsi < self.rsi_oversold:
                        signal_type = SignalType.BUY
                        confidence = min(1.0, abs(z_score) / 3)  # Max confidence at 3 std devs
                    
                    # Overbought - expect price to fall
                    elif z_score > self.std_dev_threshold and rsi > self.rsi_overbought:
                        signal_type = SignalType.SELL
                        confidence = min(1.0, abs(z_score) / 3)
                    
                    if signal_type and confidence >= 0.5:
                        expected_profit_bps = int(abs(z_score) * 50)  # 50bps per std dev
                        
                        signals.append(TradingSignal(
                            signal_id=f"MR-{secrets.token_hex(8).upper()}",
                            strategy_type=StrategyType.MEAN_REVERSION,
                            signal_type=signal_type,
                            chain_id=chain_id,
                            dex_name=dex_name,
                            token_in="USDC" if signal_type == SignalType.BUY else token,
                            token_out=token if signal_type == SignalType.BUY else "USDC",
                            amount=Decimal("0"),
                            expected_output=Decimal("0"),
                            expected_profit_bps=expected_profit_bps,
                            confidence=confidence,
                            timestamp=int(time.time()),
                            expires_at=int(time.time()) + 600,  # 10 minute validity
                            metadata={
                                'z_score': z_score,
                                'rsi': rsi,
                                'mean_price': mean_price,
                                'std_dev': std_dev,
                            }
                        ))
        
        return signals

    def _calculate_rsi(self, prices: List[float], period: int = 14) -> float:
        """Calculate RSI indicator."""
        if len(prices) < period + 1:
            return 50.0  # Neutral default
        
        gains = []
        losses = []
        
        for i in range(1, len(prices)):
            change = prices[i] - prices[i-1]
            if change > 0:
                gains.append(change)
                losses.append(0)
            else:
                gains.append(0)
                losses.append(abs(change))
        
        avg_gain = sum(gains[-period:]) / period
        avg_loss = sum(losses[-period:]) / period
        
        if avg_loss == 0:
            return 100.0
        
        rs = avg_gain / avg_loss
        rsi = 100 - (100 / (1 + rs))
        
        return rsi

    def validate_opportunity(
        self,
        signal: TradingSignal,
        current_prices: Dict[str, Decimal],
    ) -> bool:
        """Validate mean reversion signal."""
        if not signal.is_valid():
            return False
        
        # Ensure price hasn't already reverted significantly
        z_score = signal.metadata.get('z_score', 0)
        mean_price = signal.metadata.get('mean_price', 0)
        std_dev = signal.metadata.get('std_dev', 0)
        
        if not mean_price or not std_dev:
            return True
        
        token_key = f"{signal.chain_id}:{signal.dex_name}:{signal.token_out}"
        current_price = current_prices.get(token_key)
        
        if not current_price:
            return True
        
        # Calculate current z-score
        current_z = (float(current_price) - mean_price) / std_dev if std_dev else 0
        
        # Signal still valid if price is still extreme
        return abs(current_z) >= self.std_dev_threshold * 0.7


# ==============================================================================
# DCA (DOLLAR COST AVERAGING) STRATEGY
# ==============================================================================

class DCAStrategy(BaseStrategy):
    """
    Dollar Cost Averaging strategy for systematic accumulation.
    
    Automatically accumulates tokens over time to reduce timing risk.
    
    Features:
    - Scheduled purchases at regular intervals
    - Dip buying (extra buys on significant drops)
    - Multi-token portfolio support
    - Rebalancing triggers
    """

    def __init__(
        self,
        config: StrategyConfig,
        price_feed: Optional[Callable[[str, int], Decimal]] = None,
    ):
        super().__init__(config, price_feed)
        
        # DCA specific config
        self.interval_hours = config.custom_params.get('interval_hours', 24)
        self.dip_buy_threshold_pct = config.custom_params.get('dip_buy_threshold_pct', 5.0)
        self.target_allocations = config.custom_params.get('target_allocations', {})
        
        # Track last buy times
        self._last_buy_times: Dict[str, float] = {}
        self._reference_prices: Dict[str, Decimal] = {}

    def generate_signals(self, market_data: Dict[str, Any]) -> List[TradingSignal]:
        """Generate DCA signals based on schedule and dips."""
        signals = []
        
        prices = market_data.get('prices', {})
        current_time = time.time()
        interval_seconds = self.interval_hours * 3600
        
        for chain_id in self.config.chain_ids or SUPPORTED_CHAINS.keys():
            chain_prices = prices.get(chain_id, {})
            
            for dex_name in self.config.dex_names or SUPPORTED_DEXES.keys():
                dex_prices = chain_prices.get(dex_name, {})
                
                for token, current_price in dex_prices.items():
                    token_key = f"{chain_id}:{dex_name}:{token}"
                    
                    # Check if token is in target allocations
                    if self.target_allocations and token not in self.target_allocations:
                        continue
                    
                    # Check scheduled buy
                    last_buy = self._last_buy_times.get(token_key, 0)
                    scheduled_buy = (current_time - last_buy) >= interval_seconds
                    
                    # Check for dip buy
                    ref_price = self._reference_prices.get(token_key)
                    dip_buy = False
                    dip_pct = 0.0
                    
                    if ref_price and current_price < ref_price:
                        dip_pct = float((ref_price - current_price) / ref_price) * 100
                        dip_buy = dip_pct >= self.dip_buy_threshold_pct
                    
                    if scheduled_buy or dip_buy:
                        confidence = 0.7 if scheduled_buy else min(0.9, 0.5 + dip_pct / 20)
                        
                        signals.append(TradingSignal(
                            signal_id=f"DCA-{secrets.token_hex(8).upper()}",
                            strategy_type=StrategyType.DCA,
                            signal_type=SignalType.BUY,
                            chain_id=chain_id,
                            dex_name=dex_name,
                            token_in="USDC",
                            token_out=token,
                            amount=Decimal("0"),  # Calculated at execution
                            expected_output=Decimal("0"),
                            expected_profit_bps=0,  # DCA doesn't predict short-term profit
                            confidence=confidence,
                            timestamp=int(current_time),
                            expires_at=int(current_time) + 3600,  # 1 hour validity
                            metadata={
                                'trigger': 'dip' if dip_buy else 'scheduled',
                                'dip_percentage': dip_pct if dip_buy else 0,
                                'interval_hours': self.interval_hours,
                            }
                        ))
                    
                    # Update reference price (highest seen)
                    if not ref_price or current_price > ref_price:
                        self._reference_prices[token_key] = current_price
        
        return signals

    def record_execution(self, token_key: str):
        """Record that a DCA buy was executed."""
        self._last_buy_times[token_key] = time.time()

    def validate_opportunity(
        self,
        signal: TradingSignal,
        current_prices: Dict[str, Decimal],
    ) -> bool:
        """DCA signals are always valid within expiry."""
        return signal.is_valid()


# ==============================================================================
# STRATEGY MANAGER
# ==============================================================================

class StrategyManager:
    """
    Manages multiple trading strategies and coordinates execution.
    
    Features:
    - Multi-strategy coordination
    - Signal aggregation and prioritization
    - Risk budget allocation
    - Performance monitoring
    """

    def __init__(self):
        """Initialize strategy manager."""
        self._strategies: Dict[StrategyType, BaseStrategy] = {}
        self._lock = threading.Lock()
        self._is_running = False
        self._scan_thread: Optional[threading.Thread] = None
        self._pending_signals: deque = deque(maxlen=1000)

    def register_strategy(self, strategy: BaseStrategy):
        """Register a strategy with the manager."""
        with self._lock:
            self._strategies[strategy.strategy_type] = strategy
            logger.info(
                "Strategy registered: %s",
                strategy.strategy_type.value,
            )

    def unregister_strategy(self, strategy_type: StrategyType):
        """Unregister a strategy."""
        with self._lock:
            if strategy_type in self._strategies:
                del self._strategies[strategy_type]
                logger.info("Strategy unregistered: %s", strategy_type.value)

    def get_strategy(self, strategy_type: StrategyType) -> Optional[BaseStrategy]:
        """Get a registered strategy."""
        with self._lock:
            return self._strategies.get(strategy_type)

    def get_all_strategies(self) -> List[BaseStrategy]:
        """Get all registered strategies."""
        with self._lock:
            return list(self._strategies.values())

    def scan_for_signals(
        self,
        market_data: Dict[str, Any],
    ) -> List[TradingSignal]:
        """
        Scan all strategies for trading signals.
        
        Args:
            market_data: Current market state
            
        Returns:
            Aggregated list of signals from all strategies
        """
        all_signals = []
        
        with self._lock:
            strategies = list(self._strategies.values())
        
        for strategy in strategies:
            can_execute, reason = strategy.can_execute()
            if not can_execute:
                logger.debug(
                    "Strategy %s cannot execute: %s",
                    strategy.strategy_type.value,
                    reason,
                )
                continue
            
            try:
                signals = strategy.generate_signals(market_data)
                all_signals.extend(signals)
            except Exception as e:
                logger.error(
                    "Strategy %s signal generation failed: %s",
                    strategy.strategy_type.value,
                    e,
                )
        
        # Sort by confidence (highest first)
        all_signals.sort(key=lambda s: s.confidence, reverse=True)
        
        return all_signals

    def start_continuous_scanning(
        self,
        market_data_provider: Callable[[], Dict[str, Any]],
        signal_handler: Callable[[TradingSignal], None],
        interval_seconds: float = 5.0,
    ):
        """
        Start continuous market scanning.
        
        Args:
            market_data_provider: Function that returns current market data
            signal_handler: Function to handle generated signals
            interval_seconds: Scan interval
        """
        if self._is_running:
            logger.warning("Scanner already running")
            return
        
        self._is_running = True
        
        def scan_loop():
            while self._is_running:
                try:
                    market_data = market_data_provider()
                    signals = self.scan_for_signals(market_data)
                    
                    for signal in signals:
                        signal_handler(signal)
                        self._pending_signals.append(signal)
                    
                except Exception as e:
                    logger.error("Scan loop error: %s", e)
                
                time.sleep(interval_seconds)
        
        self._scan_thread = threading.Thread(target=scan_loop, daemon=True)
        self._scan_thread.start()
        logger.info("Continuous scanning started with %.1fs interval", interval_seconds)

    def stop_continuous_scanning(self):
        """Stop continuous scanning."""
        self._is_running = False
        if self._scan_thread:
            self._scan_thread.join(timeout=5.0)
            self._scan_thread = None
        logger.info("Continuous scanning stopped")

    def get_aggregated_metrics(self) -> Dict[str, StrategyMetrics]:
        """Get metrics for all strategies."""
        metrics = {}
        with self._lock:
            for strategy_type, strategy in self._strategies.items():
                metrics[strategy_type.value] = strategy.get_metrics()
        return metrics

    def pause_all(self):
        """Pause all strategies."""
        with self._lock:
            for strategy in self._strategies.values():
                strategy.pause()
        logger.info("All strategies paused")

    def resume_all(self):
        """Resume all strategies."""
        with self._lock:
            for strategy in self._strategies.values():
                strategy.resume()
        logger.info("All strategies resumed")


# ==============================================================================
# FACTORY FUNCTIONS
# ==============================================================================

def create_arbitrage_strategy(
    chain_ids: Optional[List[int]] = None,
    dex_names: Optional[List[str]] = None,
    min_profit_bps: int = 20,
) -> CrossChainArbitrageStrategy:
    """
    Create a cross-chain arbitrage strategy.
    
    Args:
        chain_ids: List of chain IDs to monitor
        dex_names: List of DEX names to monitor
        min_profit_bps: Minimum profit threshold in basis points
        
    Returns:
        Configured arbitrage strategy
    """
    config = StrategyConfig(
        strategy_type=StrategyType.ARBITRAGE,
        chain_ids=chain_ids or list(SUPPORTED_CHAINS.keys()),
        dex_names=dex_names or list(SUPPORTED_DEXES.keys()),
        min_profit_threshold_bps=min_profit_bps,
        custom_params={
            'min_profit_after_fees_bps': min_profit_bps,
        }
    )
    return CrossChainArbitrageStrategy(config)


def create_momentum_strategy(
    chain_ids: Optional[List[int]] = None,
    dex_names: Optional[List[str]] = None,
    lookback_periods: Optional[List[int]] = None,
) -> MomentumStrategy:
    """
    Create a momentum trading strategy.
    
    Args:
        chain_ids: List of chain IDs to monitor
        dex_names: List of DEX names to monitor
        lookback_periods: Timeframes for momentum calculation (in minutes)
        
    Returns:
        Configured momentum strategy
    """
    config = StrategyConfig(
        strategy_type=StrategyType.MOMENTUM,
        chain_ids=chain_ids or list(SUPPORTED_CHAINS.keys()),
        dex_names=dex_names or list(SUPPORTED_DEXES.keys()),
        custom_params={
            'lookback_periods': lookback_periods or [5, 15, 60],
            'min_trend_strength': 0.6,
        }
    )
    return MomentumStrategy(config)


def create_mean_reversion_strategy(
    chain_ids: Optional[List[int]] = None,
    dex_names: Optional[List[str]] = None,
    std_dev_threshold: float = 2.0,
) -> MeanReversionStrategy:
    """
    Create a mean reversion strategy.
    
    Args:
        chain_ids: List of chain IDs to monitor
        dex_names: List of DEX names to monitor
        std_dev_threshold: Number of standard deviations for entry
        
    Returns:
        Configured mean reversion strategy
    """
    config = StrategyConfig(
        strategy_type=StrategyType.MEAN_REVERSION,
        chain_ids=chain_ids or list(SUPPORTED_CHAINS.keys()),
        dex_names=dex_names or list(SUPPORTED_DEXES.keys()),
        custom_params={
            'std_dev_threshold': std_dev_threshold,
            'lookback_period': 20,
        }
    )
    return MeanReversionStrategy(config)


def create_dca_strategy(
    target_tokens: Dict[str, float],
    interval_hours: int = 24,
    chain_ids: Optional[List[int]] = None,
) -> DCAStrategy:
    """
    Create a DCA (Dollar Cost Averaging) strategy.
    
    Args:
        target_tokens: Dict of token -> allocation percentage
        interval_hours: Hours between scheduled buys
        chain_ids: List of chain IDs to use
        
    Returns:
        Configured DCA strategy
    """
    config = StrategyConfig(
        strategy_type=StrategyType.DCA,
        chain_ids=chain_ids or [42161, 10, 8453],  # Default to L2s for low fees
        custom_params={
            'interval_hours': interval_hours,
            'target_allocations': target_tokens,
            'dip_buy_threshold_pct': 5.0,
        }
    )
    return DCAStrategy(config)


def create_default_strategy_manager() -> StrategyManager:
    """
    Create a strategy manager with default strategies.
    
    Returns:
        Configured strategy manager with all strategies registered
    """
    manager = StrategyManager()
    
    # Register all strategies
    manager.register_strategy(create_arbitrage_strategy())
    manager.register_strategy(create_momentum_strategy())
    manager.register_strategy(create_mean_reversion_strategy())
    
    return manager


# ==============================================================================
# MODULE EXPORTS
# ==============================================================================

__all__ = [
    # Enums
    'StrategyType',
    'SignalType',
    'StrategyState',
    # Data classes
    'TradingSignal',
    'ArbitrageOpportunity',
    'StrategyConfig',
    'StrategyMetrics',
    # Strategies
    'BaseStrategy',
    'CrossChainArbitrageStrategy',
    'MomentumStrategy',
    'MeanReversionStrategy',
    'DCAStrategy',
    # Manager
    'StrategyManager',
    # Factory functions
    'create_arbitrage_strategy',
    'create_momentum_strategy',
    'create_mean_reversion_strategy',
    'create_dca_strategy',
    'create_default_strategy_manager',
]
